responseSprite:
  name: "sprites/response.png"
  width: 300
  height: 300
  col: 1
  row: 1


bgSprite: "sprites/detectiveoffice.png"
speakerLine: "There's been a murder..."
responses:
  - "Alrighty then."
  - "I'm on my way!"
  - "I see..."
  - "Not again!"