rooms: 
  - char: '.'
    name: Hallway
  - char: '0'
    name: DetectivesOffice
    sprite: sprites/detectiveoffice.png
  - char: 's'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 249
          y: 333
      - standoff: 
          scale: 240
          x: 10
          y: 334
      - standoff: 
          scale: 270
          x: 267
          y: 519
      - standoff: 
          scale: 240
          x: 492
          y: 320
      - standoff: 
          scale: 260
          x: 514
          y: 483
      - standoff: 
          scale: 240
          x: 37
          y: 532
      - prop: 
          name: lipsObj
          scale: 200
          sprite: 
            cols: 1
            height: 300
            name: sprites/response.png
            rows: 1
            width: 300
          x: 100
          y: 100
    name: Study
    sprite: sprites/study.png
  - char: 'l'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 400
          y: 464
      - standoff: 
          scale: 240
          x: 196
          y: 401
      - standoff: 
          scale: 270
          x: 280
          y: 541
      - standoff: 
          scale: 240
          x: 572
          y: 359
      - standoff: 
          scale: 260
          x: 10
          y: 537
      - standoff: 
          scale: 240
          x: 556
          y: 576
    name: Lounge
    sprite: sprites/lounge.png
  - char: 'b'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 381
          y: 361
      - standoff: 
          scale: 240
          x: 308
          y: 441
      - standoff: 
          scale: 270
          x: 446
          y: 402
      - standoff: 
          scale: 240
          x: 484
          y: 458
      - standoff: 
          scale: 260
          x: 220
          y: 595
      - standoff: 
          scale: 240
          x: 591
          y: 579
    name: Library
    sprite: sprites/library.png
  - char: 'f'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 6
          y: 437
      - standoff: 
          scale: 240
          x: 109
          y: 513
      - standoff: 
          scale: 270
          x: 448
          y: 348
      - standoff: 
          scale: 240
          x: 588
          y: 487
      - standoff: 
          scale: 260
          x: 188
          y: 336
      - standoff: 
          scale: 240
          x: 364
          y: 511
    name: Dining room
    sprite: sprites/dining.png
  - char: 'd'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 152
          y: 319
      - standoff: 
          scale: 240
          x: 454
          y: 317
      - standoff: 
          scale: 270
          x: 369
          y: 463
      - standoff: 
          scale: 240
          x: 515
          y: 488
      - standoff: 
          scale: 260
          x: 13
          y: 580
      - standoff: 
          scale: 240
          x: 627
          y: 401
    name: Billiard room
    sprite: sprites/billiards.png
  - char: 'k'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 81
          y: 506
      - standoff: 
          scale: 240
          x: 537
          y: 542
      - standoff: 
          scale: 270
          x: "-37"
          y: 320
      - standoff: 
          scale: 240
          x: 608
          y: 335
      - standoff: 
          scale: 260
          x: 292
          y: 554
      - standoff: 
          scale: 240
          x: 199
          y: 232
    name: Kitchen
    sprite: sprites/kitchen.png
  - char: 'c'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 56
          y: 530
      - standoff: 
          scale: 240
          x: 126
          y: 308
      - standoff: 
          scale: 270
          x: 492
          y: 220
      - standoff: 
          scale: 240
          x: 629
          y: 388
      - standoff: 
          scale: 260
          x: 554
          y: 560
      - standoff: 
          scale: 240
          x: 344
          y: 426
    name: Conservatory
    sprite: sprites/conservatory.png
scenes: 
  - name: conversation
  - name: intro
