rooms: 
  - char: '.'
    name: Hallway
  - char: '0'
    name: DetectivesOffice
    sprite: sprites/detectiveoffice.png
  - char: 's'
    components: 
      - type: navable
      - standoff: 
          scale: 380
          x: 211
          y: 262
      - standoff: 
          scale: 310
          x: 17
          y: 194
      - standoff: 
          scale: 320
          x: 207
          y: 449
      - standoff: 
          scale: 390
          x: 525
          y: 310
      - standoff: 
          scale: 400
          x: 475
          y: 439
      - standoff: 
          scale: 370
          x: 8
          y: 420
    name: Study
    sprite: sprites/study.png
  - char: 'l'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 400
          y: 464
      - standoff: 
          scale: 240
          x: 196
          y: 401
      - standoff: 
          scale: 270
          x: 280
          y: 541
      - standoff: 
          scale: 240
          x: 572
          y: 359
      - standoff: 
          scale: 260
          x: 10
          y: 537
      - standoff: 
          scale: 240
          x: 556
          y: 576
    name: Lounge
    sprite: sprites/lounge.png
  - char: 'b'
    components: 
      - type: navable
      - standoff: 
          scale: 160
          x: 367
          y: 297
      - standoff: 
          scale: 170
          x: 289
          y: 431
      - standoff: 
          scale: 170
          x: 468
          y: 404
      - standoff: 
          scale: 170
          x: 509
          y: 472
      - standoff: 
          scale: 200
          x: 205
          y: 579
      - standoff: 
          scale: 200
          x: 515
          y: 586
    name: Library
    sprite: sprites/library.png
  - char: 'f'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 6
          y: 437
      - standoff: 
          scale: 240
          x: 109
          y: 513
      - standoff: 
          scale: 270
          x: 448
          y: 348
      - standoff: 
          scale: 240
          x: 588
          y: 487
      - standoff: 
          scale: 260
          x: 188
          y: 336
      - standoff: 
          scale: 240
          x: 364
          y: 511
    name: Dining room
    sprite: sprites/dining.png
  - char: 'd'
    components: 
      - type: navable
      - standoff: 
          scale: 240
          x: 152
          y: 319
      - standoff: 
          scale: 240
          x: 454
          y: 317
      - standoff: 
          scale: 270
          x: 369
          y: 463
      - standoff: 
          scale: 240
          x: 515
          y: 488
      - standoff: 
          scale: 260
          x: 13
          y: 580
      - standoff: 
          scale: 240
          x: 627
          y: 401
    name: Billiard room
    sprite: sprites/billiards.png
  - char: 'k'
    components: 
      - type: navable
      - prop: 
          name: Telephone
          onclick: call
          scale: 170
          sprite: 
            name: sprites/telephone.png
          x: 477
          y: 181
      - standoff: 
          scale: 470
          x: "-92"
          y: 372
      - standoff: 
          scale: 450
          x: 488
          y: 359
      - standoff: 
          scale: 520
          x: 279
          y: 308
      - standoff: 
          scale: 470
          x: 318
          y: 336
      - standoff: 
          scale: 480
          x: 149
          y: 328
      - standoff: 
          scale: 410
          x: 42
          y: 413
    name: Kitchen
    sprite: sprites/kitchen.png
scenes: 
  - name: conversation
    responses: 
      - outcomes: 
          - motive
          - suspectMisdirect
        prompt: "What do you know about: "
        secondStep: suspect
      - outcomes: 
          - weapon
          - weaponMisdirect
        prompt: Pertaining to the murder weapon...
        secondStep: weapon
      - outcomes: 
          - accuse
        prompt: "You are under arrest!"
      - outcomes: 
          - end
        prompt: Nevermind...
    speaker: "How can I help you detective?"
  - name: intro
    responses: 
      - prompt: Alrighty then.
      - prompt: "I'm on my way!"
      - prompt: I see...
      - prompt: "Not again!"
    room: DetectivesOffice
    speaker: There's been a murder...
sprite: 
  height: 300
  name: sprites/response.png
  width: 300
