# The sprite data
width: 800
height: 800

# FIXME: Add a "navable" tag to rooms
# The room data
rooms:
  - name: Hallway
    char: '.'
  - name: Study
    char: 's'
    sprite: sprites/study.png
  - name: Lounge
    char: 'l'
    sprite: sprites/lounge.png
  - name: Library
    char: 'b'
    sprite: sprites/library.png
  - name: Dining room
    char: 'f'
    sprite: sprites/dining.png
  - name: Billiard room
    char: 'd'
    sprite: sprites/billiards.png
  - name: Kitchen
    char: 'k'
    sprite: sprites/kitchen.png
  - name: Conservatory
    char: 'c'
    sprite: sprites/conservatory.png